### ISSUE TITLE
US.7 - Custom Card Backs

### ISSUE THREAD

**Issue by Rowlandev** [Rowlandev/deck_of_cards#8]
As a user, I want to be able to choose the color of the cards so that I can personalize the game.

**Comment by matthewheck17** [comment]
est 3 hours

**Comment by bradenbatman** [comment]
> As a user, I want to be able to choose the color of the cards so that I can personalize the game.

EDIT: As a user, I want to be able to choose the back of the cards so that I can personalize the game.
